-- themes
insert into theme (theme_number, theme_parent_id, theme_name) values ('1', 1, 'Paramètres du match et sécurité'),('2', 2, 'Le jeu'), ('3', 3, 'Score'), ('4', 4, 'Pénalités'), ('5', 5, 'Arbitrage');

-- sous-themes
insert into theme (theme_number, theme_parent_id, theme_name) values ('1.1', 1, 'Structure'), ('1.2', 1, 'Equipe'), ('1.3', 1, 'Temps morts'), ('1.4', 1, 'Information du match'), ('1.5', 1, 'Victoire'), ('2.1', 2, 'La piste'), ('2.2', 2, 'Positions'), ('2.3', 2, 'Zone d’engagement et pack'), ('2.4', 2, 'Blocage et assistances'), ('2.5', 2, 'Dépassement'), ('3.1', 3, 'Marquer des points'), ('3.2', 3, 'Passages marquants '), ('3.3', 3, 'Éviter de se faire marquer'), ('3.4', 3, 'Jammeur·ses pénalisé·es'), ('3.5', 3, 'Erreurs de score et suivi du score'), ('4.1', 4, 'Pénalités de contact '), ('4.2', 4, 'Pénalités concernant la structure du match'), ('4.3', 4, 'Pénalités pour comportement antisportif (mauvaise conduite)'), ('4.4', 4, 'Mise en applications des pénalités'), ('4.5', 4, 'Exclusions et expulsions'), ('5.1', 5, 'Effectif d’arbitrage'), ('5.2', 5, 'Missions'), ('5.3', 5, 'Communication entre les patineur·ses et les officiel·les'), ('5.4', 5, 'Attribuer des pénalités');

-- sous-sous-themes
insert into theme (theme_number, theme_parent_id, theme_name) values ('1.3.1', 1, 'Temps morts d’équipe'), ('1.3.2', 1, 'Révisions d’arbitrage'), ('1.3.3', 1, 'Temps morts d’arbitrage'), ('1.5.1', 1, 'Prolongation'), ('2.2.1', 2, 'Jammeur·ses'), ('2.2.2', 2, 'Lead jammer'), ('2.2.3', 2, 'Bloqueur·se pivot '), ('2.2.4', 2, 'Star Pass (passage de l’étoile)'), ('2.2.5', 2, 'Bloqueur·ses'), ('2.4.1', 2, 'Zones cibles '), ('2.4.2', 2, 'Zones de blocage'), ('4.1.1', 4, 'Impact sur une zone cible illégale'), ('4.1.2', 4, 'Impact avec une zone de blocage illégale'), ('4.1.3', 4, 'Autre contact illégal'), ('4.1.4', 4, 'Blocages à plusieurs'), ('4.2.1', 4, 'Positionnement illégal'), ('4.2.2', 4, 'Gain de position'), ('4.2.3', 4, 'Interférer avec le déroulement du match'), ('4.2.4', 4, 'Autres procédures illégales'), ('4.4.1', 4, 'Mise en application des pénalités pour les bloqueur·ses'), ('4.4.2', 4, 'Mise en application des pénalités pour les jammeur·ses'), ('5.1.1', 5, 'Identification'), ('5.1.2', 5, 'Besoins');

-- themes (comportement des arbitres)
insert into theme (theme_number, theme_parent_id, theme_name) values ('6', 6, 'Comportement des arbitres');